### PR TITLE
Fix post limit and other issues

### PR DESCRIPTION
**Pull request by yambu**

### CODE REVIEW

**Comment by yambu** [comment]
This is my first time that i use python :-)

**Comment by k0rnh0li0** [comment]
This looks awesome dude, I'll try this out in a little while! Your "pagination" idea looks similar to how I was planning on fixing that problem :^)

Thanks for submitting this!

**Comment by yambu** [comment]
hi dear!
This is my first time using python so sorry for some logical mistakes…you could be do a better job for sure!
I’m doing this this afternoon in a couple of hours….
If u what contact me on telegram @cayambu87

Bye!


Inviato da Posta<https://go.microsoft.com/fwlink/?LinkId=550986> per Windows 10

Da: k0rnh0li0<mailto:notifications@github.com>
Inviato: domenica 27 dicembre 2020 21:51
A: k0rnh0li0/onlyfans-dl<mailto:onlyfans-dl@noreply.github.com>
Cc: Alberto Zamburlini<mailto:esperanza8787@hotmail.it>; Author<mailto:author@noreply.github.com>
Oggetto: Re: [k0rnh0li0/onlyfans-dl] Fix post limit and other issues (#7)


This looks awesome dude, I'll try this out in a little while! Your "pagination" idea looks similar to how I was planning on fixing that problem :^)

Thanks for submitting this!

**Comment by k0rnh0li0** [comment]
Looks great, I'll likely just make a few tweaks but it werks for me! Thanks again!

**Pull request merged**
